[build]
  command = "yarn build"
  publish = "build"

# Ignore the master branch on Netlify to avoid conflict with GitHub Pages
  ignore = "git rev-parse --abbrev-ref HEAD | grep -q 'master'"

# Settings specifically for the test branch
[context.test]
  command = "yarn build"
  [context.test.environment]
    NODE_ENV = "development"
    YARN_FLAGS = "--immutable"

# Add the security header to all Netlify deploys
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
